import { redirect, useActionData, useNavigation } from 'react-router-dom';
import { createOrder } from '../../services/apiRestaurant.js';
import Container from '../../ui/Container/Container';
import styles from './Order.module.scss';
import FormInput from '../../ui/Form/FormInput';
import FormRouter from '../../ui/Form/FormRouter.jsx';
import FormCheckbox from '../../ui/Form/FormCheckbox';
import FormAction from '../../ui/Form/FormAction';
import { useSelector } from 'react-redux';
import store from '../../store.js';
import { clearCart, getTotalCartPrice } from '../cart/cartSlice.js';
import { formatCurrency } from '../../utils/helpers.js';
import { useState } from 'react';

// https://uibakery.io/regex-library/phone-number
const isValidPhone = (str) =>
    /^\+?\d{1,4}?[-.\s]?\(?\d{1,3}?\)?[-.\s]?\d{1,4}[-.\s]?\d{1,4}[-.\s]?\d{1,9}$/.test(
        str
    );

export default function CreateOrder() {
  const [withPriority, setWithPriority] = useState(false);
  const username = useSelector(state => state.user.username);
  const navigation = useNavigation();
  const isSubmitting = navigation.state === 'submitting';

  const cart = useSelector(state => state.cart.cart);
  const totalCartPrice = useSelector(getTotalCartPrice);
  const priorityPrice = withPriority ? totalCartPrice * 0.2 : 0;
  const totalPrice = totalCartPrice + priorityPrice;

  const formErrors = useActionData();

  return (
      <Container narrow={true}>
        <div className={styles.orderForm}>
          <h1>Ready to order? Let's go!</h1>
          <FormRouter>
            <FormInput
                name={'customer'}
                id={'customer'}
                label={'First Name'}
                defaultValue={username}
            />
            <FormInput
                name={'phone'}
                id={'phone'}
                type={'tel'}
                label={'Phone number'}
                errorsData={formErrors}
                errorMsg={formErrors?.phone}
            />
            <FormInput
                name={'address'}
                id={'address'}
                label={'Address'}
            />
            <FormCheckbox
                name={'priority'}
                id={'priority'}
                label={'Want to give your order priority?'}
                required={false}
                value={withPriority}
                handleChange={(e) => setWithPriority(e.target.checked)}
            />
            <FormAction
                name={'cart'}
                value={JSON.stringify(cart)}
                btnName={`Order now for ${formatCurrency(totalPrice)}`}
                btnNameLoading={'Placing order...'}
                isSubmitting={isSubmitting}
                isRouterAction={true}
            />
          </FormRouter>
        </div>
      </Container>
  );
}

// When the Form is submitted, it's intercepted by this action.
export async function action({ request }) {
  const formData = await request.formData();
  const data = Object.fromEntries(formData);

  const order = {
    ...data,
    cart: JSON.parse(data.cart),
    priority: data.priority === 'true'
  };

  const errors = {};
  if (!isValidPhone(order.phone)) errors.phone = 'The phone number is not correct.';
  if (Object.keys(errors).length > 0) return errors;

  const newOrder = await createOrder(order);

  // useDispatch can't be used in simple functions,
  // so we call dispatch directly from store.
  // do NOT overuse
  store.dispatch(clearCart());

  // useNavigate can't be used in simple functions.
  // id is generated by API.
  return redirect(`/order/${newOrder.id}`);
}
