// import { useState } from 'react';
import { Form, redirect, useActionData, useNavigation } from 'react-router-dom';
import { createOrder } from '../../services/apiRestaurant.js';
import Container from '../../ui/Container/Container';
import styles from './Order.module.scss';
import Button from '../../ui/Button/Button';

// https://uibakery.io/regex-library/phone-number
const isValidPhone = (str) =>
    /^\+?\d{1,4}?[-.\s]?\(?\d{1,3}?\)?[-.\s]?\d{1,4}[-.\s]?\d{1,4}[-.\s]?\d{1,9}$/.test(
        str
    );

const fakeCart = [
  {
    pizzaId: 12,
    name: 'Mediterranean',
    quantity: 2,
    unitPrice: 16,
    totalPrice: 32,
  },
  {
    pizzaId: 6,
    name: 'Vegetale',
    quantity: 1,
    unitPrice: 13,
    totalPrice: 13,
  },
  {
    pizzaId: 11,
    name: 'Spinach and Mushroom',
    quantity: 1,
    unitPrice: 15,
    totalPrice: 15,
  },
];

export default function CreateOrder() {
  const navigation = useNavigation()
  const isSubmitting = navigation.state === 'submitting'

  const formErrors = useActionData()

  // const [withPriority, setWithPriority] = useState(false);
  const cart = fakeCart;

  return (
      <Container narrow={true}>
        <div className={styles.orderForm}>
          <h1>Ready to order? Let's go!</h1>

          {/* React router Form for POST, PATCH, DELETE. */}
          {/* No need to write action='/order/new' in this case */}
          {/* because it's automatically gets set to the current path. */}
          <Form method="POST" className={styles.form}>
            <div className={styles.formInput}>
              <label htmlFor="customer">First Name</label>
              <input type="text" name="customer" id="customer" required/>
            </div>

            <div className={styles.formInput}>
              <label htmlFor="phone">Phone number</label>
              <input type="tel" name="phone" id="phone" required/>
              {formErrors?.phone && <p className={styles.error}>{formErrors.phone}</p>}
            </div>

            <div className={styles.formInput}>
              <label htmlFor="address">Address</label>
              <input type="text" name="address" id="address" required/>
            </div>

            <div className={styles.formCheckbox}>
              <input
                  type="checkbox"
                  name="priority"
                  id="priority"
                  // value={withPriority}
                  // onChange={(e) => setWithPriority(e.target.checked)}
              />
              <label htmlFor="priority">Want to yo give your order priority?</label>
            </div>

            <div className={styles.formAction}>
              {/* Make data available in the action function. */}
              <input type="hidden" name="cart" value={JSON.stringify(cart)}/>
              <Button
                  name={isSubmitting ? 'Placing order...' : 'Order now'}
                  ariaLabel={isSubmitting ? 'Placing order...' : 'Order now'}
                  disabled={isSubmitting}
              />
            </div>
          </Form>
        </div>
      </Container>
  );
}

// When the Form is submitted, it's intercepted by this action.
export async function action({ request }) {
  const formData = await request.formData()
  const data = Object.fromEntries(formData)

  const order = {
    ...data,
    cart: JSON.parse(data.cart),
    priority: data.priority === 'on'
  }

  const errors = {}
  if (!isValidPhone(order.phone)) errors.phone = 'The phone number is not correct.'
  if (Object.keys(errors).length > 0) return errors

  const newOrder = await createOrder(order)

  // useNavigate can't be used in simple functions.
  // id is generated by API.
  return redirect(`/order/${newOrder.id}`)
}
