// import { useState } from 'react';
import { Form, redirect } from 'react-router-dom';
import { createOrder } from '../../services/apiRestaurant.js';

// https://uibakery.io/regex-library/phone-number
// const isValidPhone = (str) =>
//     /^\+?\d{1,4}?[-.\s]?\(?\d{1,3}?\)?[-.\s]?\d{1,4}[-.\s]?\d{1,4}[-.\s]?\d{1,9}$/.test(
//         str
//     );

const fakeCart = [
  {
    pizzaId: 12,
    name: 'Mediterranean',
    quantity: 2,
    unitPrice: 16,
    totalPrice: 32,
  },
  {
    pizzaId: 6,
    name: 'Vegetale',
    quantity: 1,
    unitPrice: 13,
    totalPrice: 13,
  },
  {
    pizzaId: 11,
    name: 'Spinach and Mushroom',
    quantity: 1,
    unitPrice: 15,
    totalPrice: 15,
  },
];

export default function CreateOrder() {
  // const [withPriority, setWithPriority] = useState(false);
  const cart = fakeCart;

  return (
      <div>
        <h2>Ready to order? Let's go!</h2>

        {/* React router Form for POST, PATCH, DELETE. */}
        {/* No need to write action='/order/new' in this case */}
        {/* because it's automatically gets set to the current path. */}
        <Form method="POST">
          <div>
            <label>First Name</label>
            <input type="text" name="customer" required/>
          </div>

          <div>
            <label>Phone number</label>
            <div>
              <input type="tel" name="phone" required/>
            </div>
          </div>

          <div>
            <label>Address</label>
            <div>
              <input type="text" name="address" required/>
            </div>
          </div>

          <div>
            <input
                type="checkbox"
                name="priority"
                id="priority"
                // value={withPriority}
                // onChange={(e) => setWithPriority(e.target.checked)}
            />
            <label htmlFor="priority">Want to yo give your order priority?</label>
          </div>

          <div>
            {/* Make data available in the action function. */}
            <input type='hidden' name='cart' value={JSON.stringify(cart)}/>
            <button>Order now</button>
          </div>
        </Form>
      </div>
  );
}

// When the Form is submitted, it's intercepted by this action.
export async function action({ request }) {
  const formData = await request.formData()
  const data = Object.fromEntries(formData)

  const order = {
    ...data,
    cart: JSON.parse(data.cart),
    priority: data.priority === 'on'
  }

  const newOrder = await createOrder(order)

  // useNavigate can't be used in simple functions.
  // id is generated by API.
  return redirect(`/order/${newOrder.id}`)
}
