import { createOrder, getMenu, getOrder, updateOrder } from '../services/apiRestaurant.ts';
import store from '../store';
import { clearCart } from '../features/cart/cartSlice';
import { redirect } from 'react-router-dom';

// https://uibakery.io/regex-library/phone-number
const isValidPhone = (str) =>
    /^\+?\d{1,4}?[-.\s]?\(?\d{1,3}?\)?[-.\s]?\d{1,4}[-.\s]?\d{1,4}[-.\s]?\d{1,9}$/.test(
        str
    );

//
// Load menu.
//
export async function menuLoader() {
  return await getMenu()
}

//
// Create order.
//
export async function createOrderAction({ request }) {
  const formData = await request.formData();
  const data = Object.fromEntries(formData);

  const order = {
    ...data,
    cart: JSON.parse(data.cart),
    priority: data.priority === 'true'
  };

  const errors = {};
  if (!isValidPhone(order.phone)) errors.phone = 'The phone number is not correct.';
  if (Object.keys(errors).length > 0) return errors;

  const newOrder = await createOrder(order);

  // useDispatch can't be used in simple functions,
  // so we call dispatch directly from store.
  // do NOT overuse
  store.dispatch(clearCart());

  // useNavigate can't be used in simple functions.
  // id is generated by API.
  return redirect(`/order/${newOrder.id}`);
}

//
// Get order id from url with { params }.
// useParams doesn't work in simple functions.
//
export async function orderLoader({ params }) {
  return await getOrder(params.orderId);
}

//
// Update order priority action.
//
export async function updateOrderAction({ params }) {
  const data = { priority: true };
  await updateOrder(params.orderId, data);
  return null
}
